###
GET  http://localhost:5000/blogs

###
GET  http://localhost:5000/blogs/id/In-this-blog-there-is-an-image-and-youtubekzsVN
 

###
GET http://localhost:5000/blogs/like/id/Marking-the-Web-s-35th-Birthday-An-Open-LetterezNNg

###
GET http://localhost:5000/editor/Marking-the-Web-s-35th-Birthday-An-Open-LetterezNNg